# Generated by Django 5.2.5 on 2025-09-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_comment_created_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='icon',
            field=models.ImageField(default='attachments/6522516.png', upload_to='attachments/', verbose_name='Icon'),
        ),
    ]
