# Generated by Django 5.2.5 on 2025-09-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.ImageField(default='6522516.png', upload_to='images/', verbose_name='Icon'),
        ),
    ]
