# Generated by Django 5.2.5 on 2025-09-03 10:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_user_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.ImageField(upload_to='images/', verbose_name='Attachment'),
        ),
    ]
