# Generated by Django 5.2.5 on 2025-09-09 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_forum_created_alter_attachment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='category',
            field=models.CharField(default='', max_length=200),
        ),
    ]
